/**
 * Default blocked values that come pre-configured with the extension
 * Users can unblock these if they want to see jobs from these companies/keywords
 */

const defaultBlockedValues = {
  "JobAttributeManager.linkedIn.companyName.blockedJobAttributeValues": [
    "AEROCONTACT",
    "AMD",
    "Aarorn Technologies Inc",
    "Agoda",
    "Akkodis",
    "Alignerr",
    "Altis Technology",
    "Ampstek",
    "Amyantek",
    "Arkhya Tech. Inc.",
    "Astra-North Infoteck Inc. ~ Conquering today's challenges, achieving tomorrow's vision!",
    "Avlyn Group",
    "Axiom Global Technologies",
    "Aya Healthcare",
    "Best Job Tool",
    "Biztec Global",
    "Booz Allen Hamilton",
    "Canadian Armed Forces | Forces armées canadiennes",
    "Canonical",
    "Chrome Technologies",
    "Collabera",
    "Confidential Careers",
    "Confidential Jobs",
    "Crossing Hurdles",
    "CyberCoders",
    "DataAnnotation",
    "DataStaff, Inc.",
    "Datmos",
    "Dexian",
    "Directive",
    "E-IT",
    "Emmes",
    "Emmes Group",
    "Energy Job Search",
    "FP Inc.",
    "Foilcon",
    "Forge Performance Group",
    "Galent",
    "HRConnects",
    "Hays",
    "Helic & Co.",
    "HungryPanda Ltd 熊猫外卖",
    "ImpetusIT",
    "Insight Global",
    "Iris Software Inc.",
    "J&M Group",
    "JSG (Johnson Service Group, Inc.)",
    "Jhubz by JobsMedia",
    "Jobs via Dice",
    "Jobs via eFinancialCareers",
    "Maarut Inc",
    "Mercor",
    "MillenniumSoft Inc",
    "Mindrift",
    "New York Technology Partners",
    "Northrop Grumman",
    "Odyssey Global",
    "Open Systems Technologies",
    "Peroptyx",
    "Prescient Edge",
    "Quantum World Technologies Inc.",
    "RISE Rehabilitation and Performance Centre",
    "Rackspace Technology",
    "Russell Tobin",
    "SAIC",
    "SEQ Technology LLC",
    "SPECTRAFORCE",
    "STACK IT Recruitment",
    "Silent Partners Studio",
    "Sky Systems, Inc. (SkySys)",
    "SoTalent",
    "Spark Tek Inc",
    "TELUS Digital",
    "TELUS Digital AI Data Solutions",
    "TELUS Digital Philippines",
    "TELUS International AI Data Solutions",
    "TalentAlly",
    "TalentBurst, an Inc 5000 company",
    "TalentMinded Inc.",
    "TechDoQuest",
    "TechioSoft Systems",
    "TekRek",
    "Underdog.io -Apply to top tech jobs in 60 seconds. A place where companies apply to you",
    "VBeyond Corporation",
    "VLink Inc",
    "Vibra Travels",
    "Virtusa",
    "Volunteer Success",
    "VySystems",
    "W3Global",
    "Yochana",
    "ZSA Canada",
    "myGwork - LGBTQ+ Business Community",
    "Galactic Minds INC",
    "RED TIC",
    "ITC Infotech",
    "Affinity",
    "Apptoza Inc.",
    "Havas Media Network",
    "Bevertec",
    "KTek Resourcing",
    "Robertson & Company Ltd.",
    "Akraya, Inc.",
    "Campus4Tech",
    "AspiringIT",
    "Teckhorizon Inc",
    "Tekgence Inc",
    "Infotek Consulting Services Inc.",
    "BeachHead",
    "Flexstaf I.T. Inc.",
    "Syndesus, Inc.",
    "The Select Group",
    "Hunter Bond",
    "Flexton Inc.",
    "Swoon",
    "AMISEQ",
    "Themesoft Inc.",
    "Turing",
    "OnX",
    "SP Data Digital",
    "Indotronix International Corporation",
    "Cosmo",
    "Ferrovial",
  ],
  "JobAttributeManager.linkedIn.keyword.blockedJobAttributeValues": [
    ".NET",
    "Account Executive",
    "Accountant",
    "Actuarial",
    "Administrative",
    "Administrator",
    "Advisor",
    "Architect",
    "Artist",
    "Automation Engineer",
    "Backend Engineer",
    "Bilingual",
    "Bookkeeper",
    "Bookkeeping",
    "Boucherville, QC",
    "Buyer",
    "CFO",
    "CPA",
    "Cashier",
    "Certified",
    "Chef",
    "Chief",
    "Civil Engineer",
    "Clerk",
    "Co-op",
    "Coach",
    "Consultants",
    "Coop",
    "Coordinator",
    "Cowansville, QC",
    "Cyber Security",
    "Cybersecurity",
    "DBA",
    "Data Engineer",
    "Data Entry",
    "Data Trainer",
    "DeFi",
    "Design Engineer",
    "Director",
    "Electrical Engineer",
    "Entry",
    "Expert",
    "FR",
    "Financial Analyst",
    "Financial Reporting",
    "Freelance",
    "French",
    "Front-end Developer",
    "Full Stack",
    "Full-Stack",
    "GIS",
    "Head",
    "Highspring",
    "IT",
    "Infrastructure Engineer",
    "Instructor",
    "Intern",
    "Internship",
    "Internships",
    "Investment Analyst",
    "Kinesiologist",
    "Lead",
    "Leader",
    "Lecturer",
    "Licensed",
    "MM/PP",
    "Magog, QC",
    "Manager",
    "Managers",
    "Maximo",
    "Mechanical Engineer",
    "NS2",
    "Network Engineer",
    "Nurse",
    "Officer",
    "Owner",
    "Part Time",
    "Part-time",
    "Performance Engineer",
    "PhD",
    "Pharmacist",
    "Pointe-Claire, QC",
    "Postdoc",
    "Postdoctoral",
    "President",
    "Principal",
    "Quality Assurance",
    "Recruiting",
    "Recruitment",
    "Registered",
    "Representative",
    "S/4",
    "S/4HANA",
    "SAP Systems",
    "Saint-Eustache, QC",
    "Sales Specialist",
    "Seasonal",
    "Solutions",
    "St Constant, QC",
    "Staff",
    "Staffing",
    "Summer",
    "Support Worker",
    "Talent",
    "Tax",
    "Teacher",
    "Teachers",
    "Technician",
    "Technicien",
    "Trainee",
    "Trois-Rivières",
    "Tutor",
    "VP",
    "Web3",
    "iOS",
    "security clearance",
  ],
};

export { defaultBlockedValues };
